# Generated by Django 4.2.5 on 2023-09-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('currency', models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD')], max_length=3)),
                ('ticker', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('SHOPPINGS', 'Shoppings'), ('CORPORATE_SLABS', 'Corporate Slabs'),
                            ('LOGISTICS_SHEDS', 'Logistics Sheds'), ('HOTELS', 'Hotels'),
                            ('EDUCATIONAL', 'Educational'), ('HOSPITAL', 'Hospital'), ('BANCARY', 'Bancary'),
                            ('FUNDS', 'Funds'), ('PROPERTY_DEVELOPMENT', 'Property Development'),
                            ('REAL_ESTATE_RECEIVABLES', 'Real Estate Receivables (CRIs)'),
                            ('HYBRID', 'Hybrid'), ('AGRO', 'Agro')
                        ],
                        max_length=30
                    )
                ),
                ('heritage', models.DecimalField(decimal_places=2, max_digits=18)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reservation', models.DecimalField(decimal_places=2, max_digits=18)),
                ('shareholders_amount', models.PositiveIntegerField()),
                ('quota_amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shares',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='SharePrice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shares.share')),
            ],
            options={
                'db_table': 'share_price',
                'ordering': ['share', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('currency', models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('com_data', models.DateField()),
                ('payment_date', models.DateField(null=True)),
                ('paid', models.BooleanField()),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shares.share')),
            ],
            options={
                'db_table': 'dividend',
                'ordering': ['share', '-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteShare',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shares.share')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'db_table': 'favorite_share',
                'ordering': ['share'],
                'unique_together': {('user', 'share')},
            },
        ),
    ]
